//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schema_Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        public int ActivityID { get; set; }
        public int WeekDayID { get; set; }
        public System.TimeSpan StartDate { get; set; }
        public System.TimeSpan EndDate { get; set; }
        public string ActivityDescription { get; set; }
        public string ActivityName { get; set; }
    
        public virtual WeekDay WeekDay { get; set; }
    }
}
