//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schema_Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeekDay
    {
        public WeekDay()
        {
            this.Activities = new HashSet<Activity>();
        }
    
        public int WeekDayID { get; set; }
        public string Day { get; set; }
    
        public virtual ICollection<Activity> Activities { get; set; }
    }
}
