//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schema.Domain.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivitySummery
    {
        public int ActivitySummeryId { get; set; }
        public int WeekDayId { get; set; }
        public int ActivityId { get; set; }
        public int UserId { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public System.TimeSpan EndTime { get; set; }
        public string ActivityDescription { get; set; }
    
        public virtual Activity Activity { get; set; }
        public virtual WeekDay WeekDay { get; set; }
    }
}
